accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('login/manager/', views.manager_login, name='manager_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            success_url=reverse_lazy('accounts:password_reset_done'),
            email_template_name='email_template.html'
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html',
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('list/', views.show_cart, name='show_cart'),

]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders import views

app_name = "orders"

urlpatterns = [
    path('create', views.create_order, name='create_order'),
    path('list', views.user_orders, name='user_orders'),
    path('checkout/<int:order_id>', views.checkout, name='checkout'),
    path('fake-payment/<int:order_id>', views.fake_payment, name='pay_order')
]

shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"

urlpatterns = [
	path('', views.home_page, name='home_page'),
	path('<slug:slug>', views.product_detail, name='product_detail'),
	path('add/favorites/<int:product_id>/', views.add_to_favorites, name='add_to_favorites'),
	path('remove/favorites/<int:product_id>/', views.remove_from_favorites, name='remove_from_favorites'),
	path('favorites/', views.favorites, name='favorites'),
	path('search/', views.search, name='search'),
	path('filter/<slug:slug>/', views.filter_by_category, name='filter_by_category'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify


class Category(models.Model):
    title = models.CharField(max_length=200)
    sub_category = models.ForeignKey(
        'self', on_delete=models.CASCADE,
        related_name='sub_categories', null=True, blank=True
    )
    is_sub = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs): # new
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
        

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    image = models.ImageField(upload_to='products')
    title = models.CharField(max_length=250)
    description = models.TextField()
    price = models.IntegerField()
    date_created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return self.slug
        
    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator

from shop.models import Product, Category
from cart.forms import QuantityForm


def paginat(request, list_objects):
	p = Paginator(list_objects, 20)
	page_number = request.GET.get('page')
	try:
		page_obj = p.get_page(page_number)
	except PageNotAnInteger:
		page_obj = p.page(1)
	except EmptyPage:
		page_obj = p.page(p.num_pages)
	return page_obj


def home_page(request):
	products = Product.objects.all()
	context = {'products': paginat(request ,products)}
	return render(request, 'home_page.html', context)


def product_detail(request, slug):
	form = QuantityForm()
	product = get_object_or_404(Product, slug=slug)
	related_products = Product.objects.filter(category=product.category).all()[:5]
	context = {
		'title':product.title,
		'product':product,
		'form':form,
		'favorites':'favorites',
		'related_products':related_products
	}
	if request.user.likes.filter(id=product.id).first():
		context['favorites'] = 'remove'
	return render(request, 'product_detail.html', context)


@login_required
def add_to_favorites(request, product_id):
	product = get_object_or_404(Product, id=product_id)
	request.user.likes.add(product)
	return redirect('shop:product_detail', slug=product.slug)


@login_required
def remove_from_favorites(request, product_id):
	product = get_object_or_404(Product, id=product_id)
	request.user.likes.remove(product)
	return redirect('shop:favorites')


@login_required
def favorites(request):
	products = request.user.likes.all()
	context = {'title':'Favorites', 'products':products}
	return render(request, 'favorites.html', context)


def search(request):
	query = request.GET.get('q')
	products = Product.objects.filter(title__icontains=query).all()
	context = {'products': paginat(request ,products)}
	return render(request, 'home_page.html', context)


def filter_by_category(request, slug):
	"""when user clicks on parent category
	we want to show all products in its sub-categories too
	"""
	result = []
	category = Category.objects.filter(slug=slug).first()
	[result.append(product) \
		for product in Product.objects.filter(category=category.id).all()]
	# check if category is parent then get all sub-categories
	if not category.is_sub:
		sub_categories = category.sub_categories.all()
		# get all sub-categories products 
		for category in sub_categories:
			[result.append(product) \
				for product in Product.objects.filter(category=category).all()]
	context = {'products': paginat(request ,result)}
	return render(request, 'home_page.html', context)

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <!-- bootstrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% if title %} {{ title }} {% else %} Django Online Shop {% endif %}</title>
</head>
<body>
  <header class="p-2 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <!-- cart icon -->
        {% if request.user.is_authenticated %}
        <b class="text-primary">{{ cart_count }}</b>
        {% endif %}
        <a href="{% url 'cart:show_cart' %}" class="text-primary mt-2 me-2"><i class="material-icons h3">&#xe8cc;</i></a>
        <!-- favorite icon -->
        {% if request.user.is_authenticated %}
        <b class="text-primary">{{ request.user.get_likes_count}}</b>
        {% endif %}
        <a href="{% url 'shop:favorites' %}" class="text-primary mt-2 me-2"><i class="material-icons h3">&#xe87d;</i></a>
        <!-- Menu -->
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'shop:home_page' %}" class="nav-link px-2 text-dark">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-dark">Shop</a></li>
          <!-- categories dropdown -->
          <div class="dropdown text-end">
            <a href="#" class=" mt-2 me-1 ms-1 text-dark d-block link-dark text-decoration-none dropdown-toggle"id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
            <ul class="dropdown-menu" aria-labelledby="dropdownUser1">
              {% for category in categories %}
              <!-- check if category is parent -->
                {% if not category.is_sub %}
                  <!-- parent -->
                  <li><a href="{% url 'shop:filter_by_category' category.slug %}" class="dropdown-item text-capitalize bg-light border"><b>{{ category }}</b></a></li>
                  {% for child in category.sub_categories.all %}
                   <!-- child -->
                   <li><a href="{% url 'shop:filter_by_category' child.slug %}" class="dropdown-item">{{ child }}</a></li>
                  {% endfor %}
                {% endif %}
              {% endfor %}
            </ul>
          </div>
          <li><a href="#" class="nav-link px-2 text-dark">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-dark">About</a></li>
        </ul>
        <!-- search form -->
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{% url 'shop:search' %}">
          <input name="q" type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>
        {% if request.user.is_authenticated %}
        <!-- user profile dropdown -->
        <div class="dropdown text-end">
          <a href="#" class="btn btn-primary text-white me-4 d-block link-dark text-decoration-none dropdown-toggle"id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">Profile</a>
          <ul class="dropdown-menu" aria-labelledby="dropdownUser1">
            <li><a href="{% url 'cart:show_cart' %}" <a class="dropdown-item">Cart</a></li>
            <li><a href="{% url 'shop:favorites' %}" <a class="dropdown-item">Favorites</a></li>
            <li><a href="{% url 'orders:user_orders' %}" <a class="dropdown-item">Orders</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
            <li><a class="dropdown-item text-danger" href="{% url 'accounts:user_logout' %}">Sign out</a></li>
          </ul>
        </div>
        {% else %}
        <!-- login, sign-up btn -->
        <div class="text-end">
          <a href="{% url 'accounts:user_login' %}" class="btn btn-outline-primary me-2">Login</a>
          <a href="{% url 'accounts:user_register' %}" class="btn btn-primary">Sign-up</a>
        </div>
        {% endif %}
      </div>
    </div>
  </header>
    <main class="container">
        <div class="row mt-3">
          <!-- messages -->
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
          {% endif %}
          <!-- content -->
          {% block content %}{% endblock %}
        </div>
      </main>
    <!-- Bootstrap JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/favorites.html
{% extends 'base.html' %}
{% block content %}
{% if products %}
<h2>Your Favorites</h2>
<hr>
{% for product in products %}
<div class="card me-2 mb-2" style="width: 16rem;">
  <img style="object-fit: cover;" class="card-img mt-2" width="268" height="200" src="{{ product.image.url }}">
  <div class="mt-3 text-center">
    <h5 class="card-title">{{ product.title }}</h5>
    <p class="text-muted">${{ product.price }}</p>
    <a href="{{ product.get_absolute_url }}" class="mb-3 btn btn-primary w-100">Buy Now</a>
  </div>
  <a href="{% url 'shop:remove_from_favorites' product.id %}" class="mb-3 btn btn-outline-danger">Remove</a>
</div>
{% endfor %}
{% else %}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8 mt-5 pt-5 text-center">
    <br>
    <h3 class="text-muted text-capitalize">favorites list is empty..!</h3>
    <a href="/" class="text-primary text-decoration-none">Back</a>
  </div>
  <div class="col-md-2"></div>
</div>
{% endif %}
{% endblock %}

shop/templates/home_page.html
{% extends 'base.html' %}

{% block content %}
{% if products %}
{% for product in products.object_list %}
<div class="card me-2 mb-2" style="width: 16rem;">
    <img style="object-fit: cover;" class="card-img mt-2" width="268" height="200" src="{{ product.image.url }}">
    <div class="mt-3 text-center">
      <h5 class="card-title">{{ product.title }}</h5>
      <p class="text-muted">${{ product.price }}</p>
      <a href="{{ product.get_absolute_url }}" class="mb-3 btn btn-outline-primary w-100">Buy Now</a>
    </div>
  </div>
{% endfor %}
<!-- pagination -->
<center class="mt-5">
  <div class="col-md-2">
    <ul class="pagination">
      {% if products.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">{{products.previous_page_number}}</a></li>
      {% endif %}
      <li class="page-item"><a class="page-link" href="?page={{ products.number }}">{{products.number}}</a></li>
      {% if products.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">{{products.next_page_number}}</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
      {% endif %}
    </ul>
  </div>
</center>
{% else %}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8 mt-5 pt-5 text-center">
    <br>
    <h3 class="text-muted text-capitalize">No Products..!</h3>
  </div>
  <div class="col-md-2"></div>
</div>
{% endif %}
{% endblock %}

shop/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="row mb-3 mt-4">
    <div class="col-md-1"></div>
    <!-- product content -->
    <div class="col-md-5 p-3 border rounded">
        <!-- category -->
        <div class="border-bottom mb-2 pb-2">
            <span class="text-muted ">categories:</span><a class="text-decoration-none text-dark" href="{% url 'shop:filter_by_category' product.category.slug %}"> {{product.category}}</a>
        </div>
        <!-- title -->
        <h2>{{ product.title }}</h2>
        <!-- price -->
        <h4 class="mt-4 text-dark">Price: ${{ product.price }}</h4>
        <!-- description -->
        <div class="mt-4 pe-3 mb-5">{{ product.description }}</div>
        <!-- cart btn -->
        <form method="post" action="{% url 'cart:add_to_cart' product.id %}">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="btn btn-primary mt-4" value="Add to cart">
        </form>
        <br>
        {% if favorites == 'remove' %}
        <a href="{% url 'shop:remove_from_favorites' product.id %}" class="btn btn-outline-danger mt-5 text-capitalize ">{{favorites}} from favorites</a>
        {% else %}
        <a href="{% url 'shop:add_to_favorites' product.id %}" class="btn btn-outline-success mt-5 text-capitalize ">add to {{favorites}}</a>
        {% endif %}
    </div>
    <!-- product image -->
    <div class="col-md-6">
        <img style="object-fit: cover;" class="rounded" src="{{ product.image.url }}" width="510" height="500">
    </div>
</div>
<!-- related products -->
<div class="row mt-4 mb-4">
    <h3>Related Products:</h3><hr>
    {% for p in related_products %}
        <!-- dont show the current product in this page -->
        {% if p != product %}
            <div class="card me-2 mb-2" style="width: 16rem;">
                <img style="object-fit: cover;" class="card-img mt-2" width="268" height="200" src="{{ p.image.url }}">
                <div class="mt-3 text-center">
                <h5 class="card-title">{{ p.title }}</h5>
                <p class="text-muted">${{ p.price }}</p>
                <a href="{{ p.get_absolute_url }}" class="mb-3 btn btn-outline-primary w-100">Buy Now</a>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}